# -*- coding: utf-8 -*-
"""codebuddy.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BfWiWqz3cIw3tvcpz2MNw2oayLS8P7nC
"""

# ==========================================================
#               MINI PROJECT SUBMISSION
# ==========================================================
#
# Project Title   : CodeBuddy – Coding Challenge Generator
#
# Student Name    : Arfa Bukhari
#
# Internship      : AI Powered Python Internship
#
# Program         : BS Information Technology
#
# Semester        : 3rd Semester
#
# Course          : Python Programming
#
# Platform        : MISSALPHA Learning Hub
#
# Language        : Python
#
# Technologies    : Python, HTML, CSS
#
#Submitted to     : Miss Shalini Verma
# ==========================================================
# PROJECT DESCRIPTION
# ==========================================================
#
# CodeBuddy is a beginner-friendly coding challenge
# generator developed using Python fundamentals.
#
# The program generates random programming challenges
# based on the selected language and difficulty level.
#
# Features:
# • Random Coding Challenges
# • Difficulty Selection
# • Helpful Hints
# • Learning Topics
# • HTML & CSS Report
#
# ==========================================================
# PYTHON CONCEPTS USED
# ==========================================================
#
# ✓ Variables
# ✓ Input / Output
# ✓ Data Types
# ✓ if, elif, else
# ✓ Lists
# ✓ Random Module
# ✓ HTML
# ✓ CSS
#
# ==========================================================
#                 START OF PROGRAM
# ==========================================================
# ==========================================================
# CODEBUDDY - CODING CHALLENGE GENERATOR
# PART 1
# Python + HTML + CSS
# Google Colab Compatible
# ==========================================================

from IPython.display import display, HTML
import random

# ----------------------------------------------------------
# HOME PAGE
# ----------------------------------------------------------

home = """
<html>

<head>

<style>

body{
font-family:Arial;
background:#f0f4f8;
padding:20px;
}

.container{
background:white;
width:80%;
margin:auto;
padding:20px;
border:2px solid #2c3e50;
}

h1{
text-align:center;
color:#2c3e50;
}

h2{
color:#0066cc;
}

table{
width:100%;
border-collapse:collapse;
margin-top:15px;
}

td{
border:1px solid gray;
padding:10px;
}

.footer{
margin-top:20px;
text-align:center;
color:gray;
}

</style>

</head>

<body>

<div class="container">

<h1>💻 CODEBUDDY</h1>

<h2>Coding Challenge Generator</h2>

<p>
Practice coding every day and improve your programming skills.
</p>

<table>

<tr>
<td>🎯 Random Coding Challenges</td>
</tr>

<tr>
<td>💡 Helpful Hints</td>
</tr>

<tr>
<td>📚 Topics To Learn</td>
</tr>

<tr>
<td>🏆 Completion Badge</td>
</tr>

<tr>
<td>⭐ Daily Motivation</td>
</tr>

</table>

<div class="footer">

Python + HTML + CSS

</div>

</div>

</body>

</html>

"""

display(HTML(home))

# ----------------------------------------------------------
# USER INPUT
# ----------------------------------------------------------

print("="*60)
print("WELCOME TO CODEBUDDY")
print("="*60)

name = input("Enter Your Name : ")

print("\nChoose Programming Language")
print("1. Python")
print("2. C++")
print("3. Java")
print("4. C")

choice = input("Enter Choice (1-4) : ")

if choice=="1":
    language="Python"
elif choice=="2":
    language="C++"
elif choice=="3":
    language="Java"
else:
    language="C"

print()

print("Select Difficulty")

print("1. Beginner")
print("2. Intermediate")
print("3. Advanced")

level=input("Enter Choice : ")

if level=="1":
    difficulty="Beginner"

elif level=="2":
    difficulty="Intermediate"

else:
    difficulty="Advanced"

# ----------------------------------------------------------
# CHALLENGES
# ----------------------------------------------------------

python_beginner=[

"Build a Simple Calculator",

"Guess the Number Game",

"Palindrome Checker",

"Student Grade Calculator",

"Temperature Converter"

]

cpp_beginner=[

"Even Odd Checker",

"Prime Number Checker",

"Factorial Calculator",

"Pattern Printer",

"Simple ATM Simulation"

]

java_beginner=[

"Voting Eligibility",

"Student Result System",

"Number Guessing",

"Calculator",

"Electricity Bill"

]

c_beginner=[

"Simple Calculator",

"Leap Year Checker",

"Pattern Printing",

"Number Swapping",

"Menu Driven Program"

]

if language=="Python":

    challenge=random.choice(python_beginner)

elif language=="C++":

    challenge=random.choice(cpp_beginner)

elif language=="Java":

    challenge=random.choice(java_beginner)

else:

    challenge=random.choice(c_beginner)

time_required=random.randint(20,60)

quotes=[

"Practice makes perfect.",

"Every expert was once a beginner.",

"Keep coding every day.",

"Small projects build big careers.",

"Debugging is learning."

]

quote=random.choice(quotes)

print()

print("Generating Your Coding Challenge...")
# ==========================================================
# CODEBUDDY - CODING CHALLENGE GENERATOR
# PART 2
# ==========================================================

# -------------------------------
# HINTS
# -------------------------------

if difficulty=="Beginner":

    hint="Break the problem into small steps."

    topics="Variables, Input, Output, if-else, for loop"

    badge="🥉 Beginner Coder"

elif difficulty=="Intermediate":

    hint="Use functions and loops effectively."

    topics="Functions, Lists, Loops, Strings"

    badge="🥈 Intermediate Coder"

else:

    hint="Think about logic before coding."

    topics="Problem Solving, Algorithms"

    badge="🥇 Advanced Coder"

# -------------------------------
# HTML OUTPUT
# -------------------------------

page=f"""

<html>

<head>

<style>

body{{
font-family:Arial;
background:#ffffff;
padding:20px;
}}

.container{{
width:80%;
margin:auto;
background:#f8f8f8;
border:2px solid #333;
padding:20px;
}}

h1{{
text-align:center;
color:#003366;
}}

h2{{
color:#006600;
}}

table{{
width:100%;
border-collapse:collapse;
}}

td{{
border:1px solid gray;
padding:10px;
}}

.footer{{
margin-top:20px;
text-align:center;
color:gray;
}}

</style>

</head>

<body>

<div class="container">

<h1>💻 CODEBUDDY</h1>

<h2>Your Coding Challenge</h2>

<table>

<tr>
<td><b>Name</b></td>
<td>{name}</td>
</tr>

<tr>
<td><b>Programming Language</b></td>
<td>{language}</td>
</tr>

<tr>
<td><b>Difficulty</b></td>
<td>{difficulty}</td>
</tr>

<tr>
<td><b>Challenge</b></td>
<td>{challenge}</td>
</tr>

<tr>
<td><b>Estimated Time</b></td>
<td>{time_required} Minutes</td>
</tr>

<tr>
<td><b>Hint</b></td>
<td>{hint}</td>
</tr>

<tr>
<td><b>Topics To Learn</b></td>
<td>{topics}</td>
</tr>

<tr>
<td><b>Badge</b></td>
<td>{badge}</td>
</tr>

<tr>
<td><b>Motivational Quote</b></td>
<td>"{quote}"</td>
</tr>

</table>

<br>

<h2>📋 Instructions</h2>

<ol>

<li>Read the challenge carefully.</li>

<li>Plan your solution.</li>

<li>Write your code.</li>

<li>Test with different inputs.</li>

<li>Improve your solution.</li>

</ol>

<h2>⭐ Daily Coding Tip</h2>

<p>
Spend at least 30 minutes coding every day.
Consistency is more important than speed.
</p>

<div class="footer">

Created Using Python + HTML + CSS<br>

Keep Learning • Keep Coding 🚀

</div>

</div>

</body>

</html>

"""

display(HTML(page))

print("="*60)
print("🎉 YOUR CODING CHALLENGE IS READY!")
print("="*60)

print("Challenge :", challenge)
print("Language :", language)
print("Difficulty :", difficulty)
print("Time :", time_required, "Minutes")
print("Badge :", badge)

print("\nGood Luck,", name + "!")