# -*- coding: utf-8 -*-
"""futureme

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ANKFeBs0D8LJIe2jRTGvEt9QhA5Oe22_

### **3.FUTURE ME**
"""

# ==========================================================
#               MINI PROJECT SUBMISSION
# ==========================================================
#
# Project Title   : FutureMe – Future Letter Generator
#
# Student Name    : Arfa Bukhari
#
# Internship      : AI Powered Python Internship
#
# Program         : BS Information Technology
#
# Semester        : 3rd Semester
#
# Course          : Python Programming
#
# Platform        : MISSALPHA Learning Hub
#
# Language        : Python
#
# Technologies    : Python, HTML, CSS
#
# Submitted to    : Miss Shalini Verma
# ==========================================================
# PROJECT DESCRIPTION
# ==========================================================
#
# FutureMe is a beginner-friendly application developed
# using Python fundamentals.
#
# The program allows users to write a digital letter
# to their future self, set goals, and generate
# a personalized HTML report.
#
# Features:
# • Future Letter
# • Goal Tracking
# • Personal Message
# • Motivation Quote
# • HTML & CSS Output
#
# ==========================================================
# PYTHON CONCEPTS USED
# ==========================================================
#
# ✓ Variables
# ✓ Input / Output
# ✓ Data Types
# ✓ if, elif, else
# ✓ Lists
# ✓ String Operations
# ✓ HTML
# ✓ CSS
#
# ==========================================================
#                 START OF PROGRAM
# ==========================================================
# ======================================================
# FUTUREME - DIGITAL LETTER TO MY FUTURE SELF
# PART 1
# ======================================================

from IPython.display import display, HTML
import random
from datetime import datetime

# -------------------------------
# HOME PAGE
# -------------------------------

home = """
<html>

<head>

<style>

body{
font-family:Arial;
background:#f2f2f2;
padding:20px;
}

.container{
background:white;
width:80%;
margin:auto;
padding:20px;
border:2px solid #444;
}

h1{
color:darkblue;
text-align:center;
}

h2{
color:green;
}

p{
font-size:18px;
}

table{
width:100%;
border-collapse:collapse;
}

td{
border:1px solid gray;
padding:10px;
}

.footer{
text-align:center;
color:gray;
margin-top:20px;
}

</style>

</head>

<body>

<div class="container">

<h1>🌟 FutureMe</h1>

<h2>Digital Time Capsule</h2>

<p>
Welcome!
Write a letter to your future self and save your dreams.
</p>

<table>

<tr>
<td>👤 Personal Details</td>
</tr>

<tr>
<td>🎯 Goals</td>
</tr>

<tr>
<td>💌 Future Letter</td>
</tr>

<tr>
<td>🌟 Motivation</td>
</tr>

<tr>
<td>🏆 Achievement Badge</td>
</tr>

</table>

<div class="footer">

Python + HTML + CSS

</div>

</div>

</body>

</html>

"""

display(HTML(home))

# -------------------------------
# USER INFORMATION
# -------------------------------

print("="*50)
print("WELCOME TO FUTUREME")
print("="*50)

name=input("Enter Your Name : ")

age=int(input("Enter Your Age : "))

future_year=int(input("Future Year : "))

career=input("Dream Career : ")

country=input("Dream Country : ")

print()

print("Enter Your 5 Goals")

goals=[]

for i in range(5):

    g=input(f"Goal {i+1} : ")

    goals.append(g)

print()

print("Write Your Letter")

letter=input("Message : ")

current_year=datetime.now().year

future_age=age+(future_year-current_year)

quotes=[

"Never stop learning.",

"Dream big.",

"Believe in yourself.",

"Success takes time.",

"Hard work always wins."

]

quote=random.choice(quotes)

if len(goals)==5:

    badge="🏆 Future Achiever"

else:

    badge="⭐ Dreamer"

progress=random.randint(70,100)

print()

print("Generating Your Future Letter...")

print()
# ======================================================
# FUTUREME - DIGITAL LETTER TO MY FUTURE SELF
# PART 2
# ======================================================

goal_html=""

for item in goals:

    goal_html += "<li>"+item+"</li>"

page=f"""

<html>

<head>

<style>

body{{
font-family:Arial;
background:#ffffff;
padding:20px;
}}

.box{{
width:80%;
margin:auto;
border:2px solid black;
padding:20px;
background:#f9f9f9;
}}

h1{{
text-align:center;
color:darkblue;
}}

h2{{
color:green;
}}

hr{{
border:1px solid gray;
}}

table{{
width:100%;
border-collapse:collapse;
}}

td{{
border:1px solid gray;
padding:10px;
}}

ul{{
font-size:18px;
}}

.quote{{
color:darkred;
font-style:italic;
}}

.footer{{
text-align:center;
margin-top:20px;
color:gray;
}}

</style>

</head>

<body>

<div class="box">

<h1>✉ LETTER TO MY FUTURE SELF</h1>

<hr>

<table>

<tr>

<td><b>Name</b></td>

<td>{name}</td>

</tr>

<tr>

<td><b>Current Age</b></td>

<td>{age}</td>

</tr>

<tr>

<td><b>Future Age</b></td>

<td>{future_age}</td>

</tr>

<tr>

<td><b>Future Year</b></td>

<td>{future_year}</td>

</tr>

<tr>

<td><b>Dream Career</b></td>

<td>{career}</td>

</tr>

<tr>

<td><b>Dream Country</b></td>

<td>{country}</td>

</tr>

</table>

<hr>

<h2>🎯 My Goals</h2>

<ul>

{goal_html}

</ul>

<hr>

<h2>💌 My Letter</h2>

<p>

{letter}

</p>

<hr>

<h2>🌟 Quote of the Day</h2>

<p class="quote">

"{quote}"

</p>

<hr>

<h2>🏆 Achievement Badge</h2>

<p>

{badge}

</p>

<hr>

<h2>📈 Progress</h2>

<p>

{progress}% Complete

</p>

<hr>

<div class="footer">

Created using Python + HTML + CSS

</div>

</div>

</body>

</html>

"""

display(HTML(page))

print("="*50)
print("YOUR FUTURE LETTER HAS BEEN CREATED!")
print("="*50)