# -*- coding: utf-8 -*-
"""quiz-application

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10Pn3x8uzEGJdswdRGcxj1Wpa3ok0hRtJ
"""

# ==========================================================
#      STUDENT QUIZ APPLICATION USING SDLC
# ==========================================================
#
# Project : Student Quiz Application
# Platform: Google Colab
# Language: Python
#
# Concepts Used
# ✔ Variables
# ✔ Functions
# ✔ Input
# ✔ HTML
# ✔ CSS
# ✔ SDLC
#
# ==========================================================

# Import library to display HTML
from IPython.display import display, HTML

# ==========================================================
#                SDLC - PLANNING PHASE
# ==========================================================

def planning_phase():

    print("=" * 60)
    print("         SDLC - PLANNING PHASE")
    print("=" * 60)

    print("""
Project Goal
------------
Develop a Student Quiz Application.

Objectives
----------
✔ Register Student
✔ Conduct Quiz
✔ Calculate Score
✔ Display Result
✔ Show Grade
""")

# ==========================================================
#         SDLC - REQUIREMENT ANALYSIS PHASE
# ==========================================================

def analysis_phase():

    print("=" * 60)
    print("    SDLC - REQUIREMENT ANALYSIS PHASE")
    print("=" * 60)

    print("""
INPUTS
------
• Student Name
• Roll Number
• Department
• Semester
• Quiz Answers

OUTPUTS
-------
• Score
• Percentage
• Grade
• Pass / Fail
• Result Card
""")

# ==========================================================
#              SDLC - DESIGN PHASE
# ==========================================================

def design_phase():

    html_page = """

    <!DOCTYPE html>

    <html>

    <head>

    <style>

    body{

        background:#eef5ff;
        font-family:Arial;

    }

    .container{

        width:850px;
        margin:auto;
        margin-top:30px;
        background:white;
        padding:25px;
        border-radius:12px;
        box-shadow:0px 0px 15px gray;

    }

    h1{

        color:#1565c0;
        text-align:center;

    }

    h2{

        color:#0d47a1;

    }

    p{

        font-size:18px;

    }

    ul{

        font-size:17px;

    }

    .footer{

        text-align:center;
        color:gray;
        margin-top:20px;

    }

    </style>

    </head>

    <body>

    <div class="container">

    <h1>Student Quiz Application</h1>

    <p>

    This beginner project demonstrates Software Development
    Life Cycle (SDLC) using Python, HTML and CSS.

    </p>

    <h2>Project Features</h2>

    <ul>

    <li>Student Registration</li>

    <li>Python Fundamentals Quiz</li>

    <li>Automatic Score Calculation</li>

    <li>Percentage Calculation</li>

    <li>Grade Generation</li>

    <li>Result Card</li>

    </ul>

    <div class="footer">

    Beginner Project using Python + HTML + CSS

    </div>

    </div>

    </body>

    </html>

    """

    display(HTML(html_page))

# ==========================================================
#          SDLC - IMPLEMENTATION PHASE
# ==========================================================

def student_registration():

    print("\n" + "=" * 60)
    print("      STUDENT REGISTRATION")
    print("=" * 60)

    # Taking student details

    student = {}

    student["name"] = input("Enter Student Name : ")

    student["roll"] = input("Enter Roll Number : ")

    student["department"] = input("Enter Department : ")

    student["semester"] = input("Enter Semester : ")

    print("\nRegistration Successful!")

    print("-" * 40)

    print("Name       :", student["name"])

    print("Roll No    :", student["roll"])

    print("Department :", student["department"])

    print("Semester   :", student["semester"])

    print("-" * 40)

    return student

# ==========================================================
#      CALL SDLC FUNCTIONS
# ==========================================================

planning_phase()

analysis_phase()

design_phase()

# Register student

student = student_registration()

print("\nPart 1 Completed Successfully.")

print("Next Part Will Include:")

print("✔ Quiz Questions")

print("✔ Loops")

print("✔ Lists")

print("✔ Dictionary")

print("✔ Score Calculation")
# ==========================================================
#          STUDENT QUIZ APPLICATION - PART 2
# ==========================================================
#
# PART 2 INCLUDES
# ✔ Quiz Questions
# ✔ Lists
# ✔ Dictionaries
# ✔ Loops
# ✔ Functions
# ✔ Score Calculation
#
# ==========================================================

# ----------------------------------------------------------
# FUNCTION : CREATE QUIZ QUESTIONS
# ----------------------------------------------------------

def create_questions():

    questions = [

        {
            "question":"1. Which keyword is used to create a function in Python?",
            "options":["A. class","B. function","C. def","D. create"],
            "answer":"C"
        },

        {
            "question":"2. Which symbol is used for comments in Python?",
            "options":["A. //","B. #","C. /*","D. --"],
            "answer":"B"
        },

        {
            "question":"3. Which data type stores decimal values?",
            "options":["A. int","B. float","C. bool","D. string"],
            "answer":"B"
        },

        {
            "question":"4. Which loop repeats until a condition becomes False?",
            "options":["A. for","B. if","C. while","D. switch"],
            "answer":"C"
        },

        {
            "question":"5. HTML stands for?",
            "options":[
                "A. Hyper Text Markup Language",
                "B. High Text Machine Language",
                "C. Home Tool Markup Language",
                "D. Hyper Tool Machine Language"
            ],
            "answer":"A"
        },

        {
            "question":"6. CSS is mainly used for?",
            "options":[
                "A. Database",
                "B. Styling Web Pages",
                "C. Networking",
                "D. Programming"
            ],
            "answer":"B"
        },

        {
            "question":"7. Which function displays output?",
            "options":["A. print()","B. input()","C. show()","D. display()"],
            "answer":"A"
        },

        {
            "question":"8. Which operator is used for multiplication?",
            "options":["A. +","B. -","C. *","D. /"],
            "answer":"C"
        },

        {
            "question":"9. Which keyword is used for decision making?",
            "options":["A. if","B. while","C. loop","D. repeat"],
            "answer":"A"
        },

        {
            "question":"10. Python is a ______ language.",
            "options":[
                "A. Programming",
                "B. Styling",
                "C. Markup",
                "D. Database"
            ],
            "answer":"A"
        }

    ]

    return questions


# ----------------------------------------------------------
# FUNCTION : START QUIZ
# ----------------------------------------------------------

def start_quiz(question_list):

    print("\n" + "=" * 60)
    print("         PYTHON FUNDAMENTALS QUIZ")
    print("=" * 60)

    score = 0

    # Loop through every question

    for question in question_list:

        print("\n" + question["question"])

        # Print all options

        for option in question["options"]:
            print(option)

        answer = input("Enter Option (A/B/C/D): ").upper()

        # Check answer

        if answer == question["answer"]:

            print("Correct Answer")

            score += 1

        else:

            print("Wrong Answer")

            print("Correct Answer :", question["answer"])

    return score


# ----------------------------------------------------------
# CREATE QUIZ
# ----------------------------------------------------------

quiz_questions = create_questions()

# ----------------------------------------------------------
# START QUIZ
# ----------------------------------------------------------

score = start_quiz(quiz_questions)

# ----------------------------------------------------------
# CALCULATE RESULT
# ----------------------------------------------------------

total_questions = len(quiz_questions)

percentage = (score / total_questions) * 100

print("\n" + "=" * 60)
print("           QUIZ COMPLETED")
print("=" * 60)

print("Student Name :", student["name"])
print("Correct Answers :", score)
print("Total Questions :", total_questions)
print("Percentage :", round(percentage,2), "%")

print("\nPart 2 Completed Successfully.")

print("Next Part Includes")

print("✔ Testing Phase")

print("✔ Grade")

print("✔ Pass / Fail")

print("✔ HTML Result Card")

print("✔ Maintenance Phase")
# ==========================================================
#        STUDENT QUIZ APPLICATION - PART 3
# ==========================================================
#
# PART 3 INCLUDES
# ✔ SDLC Testing Phase
# ✔ Grade Calculation
# ✔ Pass / Fail
# ✔ HTML Result Card
# ✔ SDLC Maintenance Phase
#
# ==========================================================

from IPython.display import display, HTML

# ==========================================================
#            SDLC - TESTING PHASE
# ==========================================================

def testing_phase(score, total_questions, percentage):

    print("\n" + "=" * 60)
    print("           SDLC - TESTING PHASE")
    print("=" * 60)

    # Test 1
    if score <= total_questions:
        print("✓ Score Calculation Test : Passed")
    else:
        print("✗ Score Calculation Test : Failed")

    # Test 2
    if percentage <= 100:
        print("✓ Percentage Test        : Passed")
    else:
        print("✗ Percentage Test        : Failed")

    # Test 3
    if total_questions == 10:
        print("✓ Quiz Questions Test    : Passed")
    else:
        print("✗ Quiz Questions Test    : Failed")

    print("\nTesting Completed Successfully.\n")


# ==========================================================
#             GRADE CALCULATION
# ==========================================================

def calculate_grade(percentage):

    if percentage >= 90:
        return "A+", "PASS"

    elif percentage >= 80:
        return "A", "PASS"

    elif percentage >= 70:
        return "B", "PASS"

    elif percentage >= 60:
        return "C", "PASS"

    elif percentage >= 50:
        return "D", "PASS"

    else:
        return "F", "FAIL"


# Calculate Grade

grade, status = calculate_grade(percentage)

# Run Testing

testing_phase(score, total_questions, percentage)

# ==========================================================
#               FINAL RESULT
# ==========================================================

print("=" * 60)
print("              FINAL RESULT")
print("=" * 60)

print("Student Name :", student["name"])
print("Roll Number  :", student["roll"])
print("Department   :", student["department"])
print("Semester     :", student["semester"])

print()

print("Correct Answers :", score)
print("Total Questions :", total_questions)
print("Percentage      :", round(percentage,2), "%")
print("Grade           :", grade)
print("Status          :", status)

# ==========================================================
#              HTML RESULT CARD
# ==========================================================

status_color = "green" if status == "PASS" else "red"

html_result = f"""

<!DOCTYPE html>

<html>

<head>

<style>

body{{
background:#eef5ff;
font-family:Arial;
}}

.card{{
width:750px;
margin:auto;
margin-top:30px;
background:white;
padding:25px;
border-radius:12px;
box-shadow:0px 0px 12px gray;
}}

h1{{
text-align:center;
color:#1565c0;
}}

table{{
width:100%;
border-collapse:collapse;
margin-top:20px;
}}

th{{
background:#1565c0;
color:white;
padding:12px;
}}

td{{
padding:12px;
border:1px solid #cccccc;
}}

.status{{
text-align:center;
font-size:26px;
font-weight:bold;
color:{status_color};
margin-top:20px;
}}

.footer{{
text-align:center;
color:gray;
margin-top:20px;
}}

</style>

</head>

<body>

<div class="card">

<h1>Student Quiz Result</h1>

<table>

<tr>

<th>Field</th>

<th>Information</th>

</tr>

<tr>

<td>Name</td>

<td>{student["name"]}</td>

</tr>

<tr>

<td>Roll Number</td>

<td>{student["roll"]}</td>

</tr>

<tr>

<td>Department</td>

<td>{student["department"]}</td>

</tr>

<tr>

<td>Semester</td>

<td>{student["semester"]}</td>

</tr>

<tr>

<td>Total Questions</td>

<td>{total_questions}</td>

</tr>

<tr>

<td>Correct Answers</td>

<td>{score}</td>

</tr>

<tr>

<td>Percentage</td>

<td>{percentage:.2f}%</td>

</tr>

<tr>

<td>Grade</td>

<td>{grade}</td>

</tr>

</table>

<div class="status">

{status}

</div>

<div class="footer">

<b>Congratulations!</b>

<br><br>

This project demonstrates:

<br><br>

✔ SDLC Methodology<br>
✔ Python Fundamentals<br>
✔ HTML & CSS<br>
✔ Functions<br>
✔ Loops<br>
✔ Lists<br>
✔ Dictionaries<br>
✔ Conditions<br>
✔ Student Management<br>
✔ Quiz System

</div>

</div>

</body>

</html>

"""

display(HTML(html_result))

# ==========================================================
#          SDLC - MAINTENANCE PHASE
# ==========================================================

def maintenance_phase():

    print("\n" + "=" * 60)
    print("         SDLC - MAINTENANCE PHASE")
    print("=" * 60)

    future_features = [

        "Student Login System",

        "Database Integration",

        "Random Quiz Questions",

        "Quiz Timer",

        "Leaderboard",

        "Download Result as PDF",

        "Export Results to Excel",

        "Question Categories"

    ]

    print("Future Improvements:\n")

    for feature in future_features:

        print("✓", feature)


maintenance_phase()

# ==========================================================
#            PROJECT COMPLETED
# ==========================================================

print("\n" + "=" * 60)
print("      PROJECT COMPLETED SUCCESSFULLY")
print("=" * 60)

print("Thank you for using the Student Quiz Application.")
print("Keep learning Python and SDLC!")
print("Good Luck!")