# -*- coding: utf-8 -*-
"""SkillQuest – Career Discovery.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BfWiWqz3cIw3tvcpz2MNw2oayLS8P7nC
"""

# ==========================================================
#               MINI PROJECT SUBMISSION
# ==========================================================
#
# Project Title   : SkillQuest – Career Discovery
#
# Student Name    : Arfa Bukhari
#
# Internship      : AI Powered Python Internship
#
# Program         : BS Information Technology
#
# Semester        : 3rd Semester
#
# Course          : Python Programming
#
# Platform        : MISSALPHA Learning Hub
#
# Language        : Python
#
# Technologies    : Python, HTML, CSS
#
#Submitted to     : Miss Shalini Verma
# ==========================================================
# PROJECT DESCRIPTION
# ==========================================================
#
# SkillQuest is a beginner-friendly career discovery
# application developed using Python fundamentals.
#
# The program recommends a suitable technology career
# based on the user's interests, strengths, and skill level.
#
# Features:
# • Career Recommendation
# • Required Skills
# • Learning Roadmap
# • Motivation Quote
# • HTML & CSS Career Report
#
# ==========================================================
# PYTHON CONCEPTS USED
# ==========================================================
#
# ✓ Variables
# ✓ Input / Output
# ✓ Data Types
# ✓ if, elif, else
# ✓ for Loop
# ✓ Lists
# ✓ Random Module
# ✓ HTML
# ✓ CSS
#
# ==========================================================
#                 START OF PROGRAM
# ==========================================================
# ==========================================================
# SKILLQUEST - CAREER DISCOVERY
# PART 1
# Python + HTML + CSS
# Google Colab Compatible
# ==========================================================

from IPython.display import display, HTML
import random

# -----------------------------
# HOME PAGE
# -----------------------------

home = """
<html>

<head>

<style>

body{
font-family:Arial;
background:#f2f2f2;
padding:20px;
}

.container{
width:80%;
margin:auto;
background:white;
padding:20px;
border:2px solid black;
}

h1{
text-align:center;
color:darkblue;
}

h2{
color:green;
}

table{
width:100%;
border-collapse:collapse;
margin-top:15px;
}

td{
border:1px solid gray;
padding:10px;
}

.footer{
text-align:center;
margin-top:20px;
color:gray;
}

</style>

</head>

<body>

<div class="container">

<h1>🎯 SKILLQUEST</h1>

<h2>Career Discovery System</h2>

<p>
Discover the best career according to your interests,
favorite subjects and strengths.
</p>

<table>

<tr>
<td>💼 Career Recommendation</td>
</tr>

<tr>
<td>📚 Skills Required</td>
</tr>

<tr>
<td>🛣 Learning Roadmap</td>
</tr>

<tr>
<td>🌟 Motivation</td>
</tr>

<tr>
<td>🏆 Career Report</td>
</tr>

</table>

<div class="footer">

Python + HTML + CSS

</div>

</div>

</body>

</html>

"""

display(HTML(home))

# -----------------------------
# USER DETAILS
# -----------------------------

print("="*60)
print("WELCOME TO SKILLQUEST")
print("="*60)

name=input("Enter Your Name : ")

print()

print("Choose Your Interest")

print("1. Artificial Intelligence")
print("2. Web Development")
print("3. Data Science")
print("4. Cyber Security")
print("5. Mobile App Development")
print("6. UI/UX Design")

interest=input("Enter Choice : ")

print()

subject=input("Favorite Subject : ")

strength=input("Your Biggest Strength : ")

print()

print("Choose Your Skill Level")

print("1. Beginner")
print("2. Intermediate")
print("3. Advanced")

level=input("Enter Choice : ")

# -----------------------------
# CAREER DECISION
# -----------------------------

if interest=="1":

    career="AI Engineer"

    skills="Python, Machine Learning, Mathematics"

    roadmap="Learn Python -> AI Basics -> Machine Learning"

elif interest=="2":

    career="Web Developer"

    skills="HTML, CSS, JavaScript, Python"

    roadmap="HTML -> CSS -> Python -> Frameworks"

elif interest=="3":

    career="Data Analyst"

    skills="Python, Excel, SQL"

    roadmap="Excel -> SQL -> Python -> Visualization"

elif interest=="4":

    career="Cyber Security Analyst"

    skills="Networking, Linux, Python"

    roadmap="Networking -> Linux -> Security"

elif interest=="5":

    career="Android Developer"

    skills="Java, Kotlin, XML"

    roadmap="Java -> Android Studio -> Projects"

else:

    career="UI/UX Designer"

    skills="Figma, Design Thinking"

    roadmap="UI Basics -> UX -> Portfolio"

quotes=[

"Success begins with learning.",

"Practice every day.",

"Dream big and work hard.",

"Skills create opportunities.",

"Consistency beats talent."

]

quote=random.choice(quotes)

progress=random.randint(70,100)

print()

print("Generating Career Report...")
# ==========================================================
# SKILLQUEST - CAREER DISCOVERY
# PART 2
# CAREER REPORT
# ==========================================================

if level=="1":

    level_name="Beginner"

    badge="🥉 Beginner Learner"

elif level=="2":

    level_name="Intermediate"

    badge="🥈 Growing Professional"

else:

    level_name="Advanced"

    badge="🥇 Future Expert"

report=f"""

<html>

<head>

<style>

body{{
font-family:Arial;
background:#ffffff;
padding:20px;
}}

.container{{
width:80%;
margin:auto;
background:#f8f8f8;
border:2px solid black;
padding:20px;
}}

h1{{
text-align:center;
color:darkblue;
}}

h2{{
color:green;
}}

table{{
width:100%;
border-collapse:collapse;
margin-top:15px;
}}

td{{
border:1px solid gray;
padding:10px;
}}

.footer{{
text-align:center;
margin-top:20px;
color:gray;
}}

</style>

</head>

<body>

<div class="container">

<h1>🎯 SKILLQUEST CAREER REPORT</h1>

<h2>Your Career Profile</h2>

<table>

<tr>
<td><b>Name</b></td>
<td>{name}</td>
</tr>

<tr>
<td><b>Favorite Subject</b></td>
<td>{subject}</td>
</tr>

<tr>
<td><b>Strength</b></td>
<td>{strength}</td>
</tr>

<tr>
<td><b>Skill Level</b></td>
<td>{level_name}</td>
</tr>

<tr>
<td><b>Recommended Career</b></td>
<td>{career}</td>
</tr>

<tr>
<td><b>Required Skills</b></td>
<td>{skills}</td>
</tr>

<tr>
<td><b>Learning Roadmap</b></td>
<td>{roadmap}</td>
</tr>

<tr>
<td><b>Progress Level</b></td>
<td>{progress}%</td>
</tr>

<tr>
<td><b>Achievement Badge</b></td>
<td>{badge}</td>
</tr>

</table>

<br>

<h2>🌟 Motivation Quote</h2>

<p>

"{quote}"

</p>

<br>

<h2>📚 Your Learning Plan</h2>

<ol>

<li>Build strong programming fundamentals.</li>

<li>Practice coding every day.</li>

<li>Create mini projects.</li>

<li>Learn Git and GitHub.</li>

<li>Build your portfolio.</li>

<li>Apply for internships.</li>

<li>Continue learning new technologies.</li>

</ol>

<br>

<h2>🏆 Final Message</h2>

<p>

Congratulations <b>{name}</b>!

Your recommended career is
<b>{career}</b>.

Stay consistent, complete projects,
and keep improving your skills.

</p>

<div class="footer">

Created using Python + HTML + CSS

<br>

SkillQuest Career Discovery System

</div>

</div>

</body>

</html>

"""

display(HTML(report))

print("="*60)
print("🎉 CAREER REPORT GENERATED SUCCESSFULLY!")
print("="*60)

print("Name :",name)
print("Career :",career)
print("Level :",level_name)
print("Progress :",progress,"%")
print("Badge :",badge)

print("\nThank you for using SkillQuest!")